### ISSUE TITLE
Compatible with Rails 4.2?

### ISSUE THREAD

**Issue by yoonwaiyan** [smashingboxes/cardboard#129]
Hi, since the README.md mentioned that this gem supports Rails 4.x, I've tried to create a new Rails 4.2 app and added the gem to gemfile and run `bundle install`, but I got an error message that seems like the gem only supports 4.0. Does it really support Rails 4.x anyway?

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    cardboard_cms (>= 0) ruby depends on
      rails (~> 4.0.0) ruby

    rails (4.2.0)
```

**Comment by iandonovan** [comment]
Hi!

The master branch tentatively supports Rails 4.2., but it hasn't gone through our testing/release process. I believe we ~officially~ support 4.1.x, but if you like "living on the edge," feel free to base your gemfile off the master branch.

Thanks for using Cardboard!
Ian
