### ISSUE TITLE
Imagine a nicer way of showing repeatable parts!

### ISSUE THREAD

**Issue by leonelgalan** [smashingboxes/cardboard#4]
We show them vertically now, but it's hard to tell that all parts belong to a collection. We need ideas, sketches on how to improve this!

![screen shot 2013-05-13 at 3 39 24 pm](https://f.cloud.github.com/assets/311279/497790/e082b196-bc04-11e2-9741-d678c4104e30.png)

See how a second part starts at the bottom? It's not very clear that this belong together.

**Comment by joeyjoejoejr** [comment]
I think this was fixed. Reopen if it's still an issue.
