### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by elfassy** [smashingboxes/cardboard#8]
**page views**: We could implement our own page views count, or simply hook up to google analytics api (but there's a max).

We should probably design some widgets (number, gage...) that can be used on the dashboard.

2457 VISITS Today
3240 USERS February 2013
322 ORDERS This week
$2,340 SALES

**Comment by joeyjoejoejr** [comment]
Closing this, we should open another discussion about what to do with the dashboard
