### ISSUE TITLE
Grid system revision

### ISSUE THREAD

**Issue by joshvc** [smashingboxes/cardboard#93]
Bootstrap has a pretty effective native responsive grid system- need to evaluate if it's worth rebuilding the admin interface with it.

**Comment by joeyjoejoejr** [comment]
@joshvc I did a fair amount of this.  I think the only part that is not responsive is the cms part.

**Comment by joshvc** [comment]
Yeah, I don't think the grid system needs to be revised in light of the work you got done in the fall. I think this ticket can close, and if we want to create one to improve responsiveness that can be its own conversation.
